spaceone-dev/console

src/components/molecules/tabs/tab-bar/toolset.ts, src/lib/api/table.ts, src/views/common/widgets/cloud-services/CloudServices.vue, src/views/common/widgets/daily-updates/DailyUpdates.vue, src/views/common/widgets/resources-by-region/ResourcesByRegion.toolset.ts, src/views/common/widgets/resources-by-region/ResourcesByRegion.vue, src/views/project/project/pages/ProjectDashboard.vue
Signed-off-by: siyeon <sylee@megazone.com>
=> Add project filter to widgets

src/views/project/project/pages/ProjectPage.vue
Signed-off-by: siyeon <sylee@megazone.com>
=> HotFix apiHandler action in project

src/components/molecules/layouts/grid-layout/toolset.ts, src/components/molecules/tree-origin/Tree.vue, src/components/organisms/dynamic-view/dynamic-layout/templates/table/index.vue, src/components/organisms/layouts/toolbox-grid-layout/toolset.ts, src/lib/api/grid.ts, src/lib/api/table.ts, src/routes/inventory/inventory-route.js, src/views/identity/service-account/pages/ServiceAccount.vue, src/views/inventory/cloud-service/pages/CloudServicePage.vue, src/views/inventory/cloud-service/pages/CloudServiceType.vue, src/views/project/project/pages/ProjectDetail.vue, src/views/project/project/pages/ProjectPage.vue
Feature 추가
[Cloud service] 메인 페이지 링크 이슈(뒤로가기 시 필터, 검색 없어지는 건) 해결
2.   [Project] Project ID 페이지에 명세
3.   [Project] Project 대시보드 내 Cloud Service 클릭 후 뒤로가기 버튼(화면 내) 누를 시 대시보드로 돌아오도록 UX 변경
4.   [Service Account] Service Account ID를 테이블/Details에 추가
BugFix
pagination - 페이지 변경 시 검색이 안되는 이슈 해결
=> Fix router issue and minor css

public/index.html, src/components/organisms/layouts/vertical-layout/VerticalLayout.vue, src/lib/api/tree-node.ts, src/views/project/project/modules/ProjectCreateFormModal.vue, src/views/project/project/pages/ProjectPage.vue
1. 프로젝트 이름 수정 버그픽스
2. Vertical layout의 트리 숨김 효과 수정
=> HotFix bugs in project page

src/lib/api/tree-node.ts, src/lib/chart/line-chart.ts, src/lib/chart/s-chart.ts, src/views/common/widgets/service-summary/ServiceSummary.toolset.ts, src/views/common/widgets/service-summary/ServiceSummary.vue, src/views/project/project/pages/ProjectDetail.vue
1. Service Summary widget 컴포넌트 차트 수정
2. Project 대시보드 ID 복사 기능 추가
=> Service Summary chart updated 

public/index.html, src/components/organisms/layouts/vertical-layout/VerticalLayout.vue, src/lib/api/tree-node.ts, src/views/project/project/pages/ProjectDetail.vue
- [Service Summary] widget label updated
- [Top 5 Projects] widget label updated
- [Collection History] widget label updated
=> Dashboard > Chart labeling updated

src/lib/display-formatter.ts, src/store/toolset.ts, src/views/common/widgets/daily-updates/DailyUpdates.vue, src/views/identity/service-account/pages/ServiceAccount.vue, src/views/inventory/server/Server.vue
1. BugFix project formatting in server and service account
2. BugFix in daily updates widget
=> BugFix project name formatting and Daily updates

src/store/modules/domain/actions.ts, src/store/modules/domain/index.ts, src/store/modules/domain/mutations.ts, src/store/modules/domain/type.ts
=> Add plugin options and metadata to domain store

src/store/modules/user/plugins.ts
=> Bug fix: domain store reset issue

src/store/modules/domain/actions.ts, src/store/modules/domain/getters.ts, src/store/modules/domain/index.ts, src/store/modules/domain/mutations.ts, src/store/modules/domain/type.ts, src/views/sign-in/Signin.vue
Change authType to authSystem in domain store
=> Add authType(INTERNAL | EXTERNAL) to domain store

src/views/automation/power-scheduler/pages/PowerSchedulerPage.vue
=> Change power schedule's default sorting

src/store/modules/resource/index.ts
=> Add project group and cloud service type to resource store

src/store/modules/user/actions.ts, src/store/modules/user/index.ts, src/store/modules/user/mutations.ts, src/store/modules/user/type.ts
=> Add a powerSchedulerState to use store

src/main.ts
=> Remove store.logout function when session expired

src/main.ts
=> Bug fix: domain load issue in sign in page

src/store/modules/resource/actions.ts, src/store/modules/resource/index.ts, src/store/modules/resource/plugin/actions.ts, src/store/modules/resource/plugin/getters.ts, src/store/modules/resource/plugin/index.ts, src/store/modules/resource/plugin/mutations.ts
=> Add a plugin resource store

src/main.ts, src/routes/index.ts, src/store/modules/user/actions.ts, src/store/modules/user/index.ts, src/store/modules/user/mutations.ts, src/store/modules/user/type.ts
Add a isSignedIn state to user store
=> Add a isSignedIn state to user store 

src/store/modules/resource/cloud-service-type/actions.ts, src/store/modules/resource/collector/actions.ts, src/store/modules/resource/plugin/actions.ts, src/store/modules/resource/provider/actions.ts
=> Bug fix: tags format issue

src/App.vue, src/main.ts, src/routes/index.ts, src/store/modules/user/actions.ts, src/store/modules/user/index.ts, src/store/modules/user/mutations.ts, src/store/modules/user/type.ts, src/views/identity/user/User.vue
Added sessionExpired property to store and applied to session callback function.
sessionExpired property is used to show modal that notify the session is expired.
=> Add: sessionExpired property to store 

src/store/modules/domain/actions.ts, src/store/modules/domain/index.ts, src/store/modules/domain/type.ts
=> Add extendedAuthType field to domain store

src/store/modules/user/actions.ts, src/store/modules/user/getters.ts, src/store/modules/user/index.ts, src/store/modules/user/mutations.ts, src/store/modules/user/type.ts, src/views/common/components/profile/ProfileModal.vue, src/views/sign-in/pages/Domain_Admin_SignIn.vue, src/views/sign-in/pages/SignIn.vue, src/views/sign-in/templates/GOOGLE_OAUTH2.vue, src/views/sign-in/templates/ID_PW.vue
=> Change a issue token api format

src/views/sign-in/templates/GOOGLE_OAUTH2.vue
=> Bug fix: Fix bug getting user email from google oauth2

src/store/modules/user/actions.ts, src/store/modules/user/config.ts, src/store/modules/user/getters.ts, src/store/modules/user/index.ts, src/store/modules/user/mutations.ts, src/store/modules/user/type.ts
=> Add roles field to user store

src/store/modules/resource/actions.ts, src/store/modules/resource/index.ts, src/store/modules/resource/region/actions.ts, src/store/modules/resource/user/actions.ts, src/store/modules/resource/user/getters.ts, src/store/modules/resource/user/index.ts, src/store/modules/resource/user/mutations.ts
=> Add resource user store

src/store/modules/user/actions.ts
=> Add roles fields to user store

src/store/modules/user/actions.ts
=> fix a role binding load error

package-lock.json, package.json, src/store/modules/resource/cloud-service-type/actions.ts, src/store/modules/resource/collector/actions.ts, src/store/modules/resource/plugin/actions.ts, src/store/modules/resource/project-group/actions.ts, src/store/modules/resource/project/actions.ts, src/store/modules/resource/region/actions.ts, src/store/modules/resource/secret/actions.ts, src/store/modules/resource/service-account/actions.ts, src/store/modules/resource/user/actions.ts, src/views/automation/power-scheduler/pages/ResourceGroupPage.vue, src/views/identity/service-account/pages/ServiceAccountPage.vue, src/views/inventory/cloud-service/pages/CloudServicePage.vue, src/views/inventory/cloud-service/pages/CloudServiceType.vue, src/views/inventory/server/modules/ServerMain.vue
=> Update  typeOptions props in DynamicLayout used pages

package-lock.json, package.json, src/views/automation/power-scheduler/pages/ResourceGroupPage.vue, src/views/identity/service-account/pages/ServiceAccountPage.vue, src/views/inventory/cloud-service/pages/CloudServicePage.vue, src/views/inventory/server/modules/ServerMain.vue
다이나믹 레이아웃 typeOptions, fetchOptions 사용하는 방법 개선
다이나믹 레이아웃의 typeOptions, fetchOptions를 사용하는 페이지에서 타입 정의 방식이 복잡하고 길어서 그 방식을 개선함
=> Update DynamicLayout type usages

package-lock.json, package.json, src/lib/component-utils/dynamic-layout/index.ts, src/store/modules/file/type.ts, src/views/automation/spot-automation/modules/SchedulePolicySettings.vue, src/views/automation/spot-automation/pages/AddSpotGroupPage.vue, src/views/plugin/collector/modules/EditScheduleModal.vue, src/views/plugin/collector/pages/CreateCollectorPage.vue, src/views/sign-in/templates/ID_PW.vue
Update default value of schedule policy in add spot group page
=> Update default value of schedule policy in add spot group page

src/store/modules/resource/cloud-service-type/actions.ts, src/store/modules/resource/collector/actions.ts, src/store/modules/resource/plugin/actions.ts, src/store/modules/resource/provider/actions.ts
Store 내 tags 데이터를 처리하는 로직 변경
[{key: <key>, value: <value>}, ...] 형태의 tags를 {<key>: <value>} 형태로 변경
SpaceONE 내 전체 tags 형식이 바뀐것이기 때문에 Store 외에 다른 부분도 추가 처리 필요
=> Change tags format in store

src/common/components/charts/metric-chart/MetricChart.vue, src/services/automation/spot-automation/components/OnDemandAndSpotChart.vue, src/services/automation/spot-automation/modules/InstanceBillingChart.vue, src/services/automation/spot-automation/modules/SpotGroupRatioChart.vue, src/services/automation/spot-automation/spot-group/components/SpotInterruptChart.vue, src/services/automation/spot-automation/spot-group/spot-group-detail/modules/SpotGroupDetailDashboardBaseInfo.vue, src/services/automation/spot-automation/spot-group/spot-group-detail/modules/SpotGroupDetailDashboardInterrupt.vue, src/services/billing/cost-management/budget/budget-detail/modules/budget-summary/BudgetSummaryChart.vue, src/services/billing/cost-management/cost-analysis/modules/CostAnalysisPieChart.vue, src/services/billing/cost-management/cost-analysis/modules/CostAnalysisStackedColumnChart.vue, src/services/billing/cost-management/widgets/BudgetStatus.vue, src/services/billing/cost-management/widgets/CostDonut.vue, src/services/billing/cost-management/widgets/CostPie.vue, src/services/billing/cost-management/widgets/CostTreeMap.vue, src/services/billing/cost-management/widgets/CostTrendLine.vue, src/services/billing/cost-management/widgets/modules/CostDashboardStackedColumnWidget.vue, src/services/dashboard/modules/AllSummary.vue, src/services/dashboard/modules/ResourceMap.vue, src/services/dashboard/modules/ServiceAccounts.vue, src/services/dashboard/modules/TopProjects.vue, src/services/management/collector-history/modules/CollectorHistoryChart.vue, src/services/monitoring/alert-manager/alert-dashboard/modules/CurrentProjectStatusWidget.vue, src/services/monitoring/alert-manager/alert-dashboard/modules/alert-history-widget/AlertHistoryChart.vue, src/services/project/project-detail/project-summary/modules/ProjectAllSummary.vue, src/services/project/project-detail/project-summary/modules/ProjectBilling.vue, src/services/project/project-detail/project-summary/modules/ProjectRegionService.vue
PChartLoader 를 PDataLoader 로 교체하였습니다.
컴포넌트 확인이 가능한 부분들은 기존 PChartLoader 작동 방식을 확인한 뒤,
loading 값을 false 로 고정해둔 상태에서 PDataLoader 로 변경하여 테스트하였습니다.
컴포넌트 확인이 가능하지 않거나 어려운 부분들은 교체작업만 해 두었으며,
사용되지 않는 서비스 내 컴포넌트들은 변경하지 않고 주석만 달아두었습니다.
=> chore: refactor PChartLoader to PDataLoader

Dockerfile, packages/@spaceone/console-core-lib/src/query/index.ts
=> ci: remove computed type declaration in core-lib & update dockerfile

package-lock.json, package.json
다이나믹 레이아웃 popup 템플릿 수정사항 반영입니다.
=> chore: update design-system version

src/services/asset-inventory/cloud-service/cloud-service-detail/modules/CloudServiceHistory.vue, src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceHistoryDetailNoteTab.vue, src/services/asset-inventory/cloud-service/cloud-service-detail/modules/cloud-service-history-detail/CloudServiceHistoryDetailOverlay.vue
- [] 신규 기능
노트 추가/삭제 시 vertical timeline에도 count가 반영되도록 수정하였습니다.
=> fix: add refreshNoteCount event to CloudServiceHistoryDetailOverlay

packages/@spaceone/console-core-lib/src/space-connector/api.ts, packages/@spaceone/console-core-lib/src/space-connector/index.ts
=> fix(core lib): make on off token check interval in space connector

package-lock.json, package.json, packages/@spaceone/console-core-lib/src/space-connector/api.ts, src/services/alert-manager/escalation-policy/modules/EscalationPolicyForm.vue
- anchor 컴포넌트 수정사항이 디자인 시템 버전을 업그레이드하면서 반영되어서, escalation policy form 에 커스텀 스타일로 들어가있던 부분을 뺐습니다.
커스텀 스타일은 최대한 자제하는게 좋을것 같아요.
콘솔에서 추가적인 작업을 하는 것이, 디자인 시스템 컴포넌트를 재사용함으로써 얻는 효율성을 낮추는 것 같습니다.
=> fix: fix wrong style in escalation policy form and update design system version for dynamic field bug fix

src/common/modules/navigations/gnb/modules/gnb-noti/modules/GNBNoticeTab.vue, src/lib/helper/notice-helper.ts, src/services/info/notice/NoticePage.vue, src/services/info/notice/modules/NoticeList.vue, src/services/info/notice/modules/list-item/ListItem.vue
list api 연결입니다.
아직 추가되지 않은 기능
- 키워드 검색과 페이지네이션
- pinned 와 inNew
notice에 뭔가 같이 사용될만한 요청들이 조금 있는것 같습니다.
예시로 boardId가져오는 함수를 하나 뽑아봤습니다
=> feat(notice-list): connect list api to notice-list

src/services/info/notice/modules/list-item/ListItem.vue, src/services/info/notice/notice-detail/NoticeDetailPage.vue
- notice detail page에서 불릿 타입 리스트 아이콘 짤림 수정
- 없는 post의 경우 next, prev 라벨 제거 및 스타일 수정
=> fix(notice-detail): fix style of notice-detail & notice-item
